apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: sekiban-events-subscription
spec:
  topic: sekiban-events
  routes:
    default: /dapr/subscribe/sekiban-events
  pubsubname: pubsub
scopes:
- daprsekiban-apiservice