apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: domain-events-subscription
spec:
  topic: events.all
  routes:
    default: /internal/pubsub/events
  pubsubname: sekiban-pubsub
scopes:
- sekiban-event-relay