apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: domain-events-subscription
spec:
  topic: domain-events
  routes:
    default: /events
  pubsubname: sekiban-pubsub
scopes:
- sekiban-api