<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>$(SekibanCoreNet8Net9TargetFrameworks)</TargetFrameworks>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Sekiban.Core.DotNet\Sekiban.Core.DotNet.csproj"/>
        <ProjectReference Include="..\Shipping.Domain\Shipping.Domain.csproj"/>
        <ProjectReference Include="..\Warehouse.Domain\Warehouse.Domain.csproj"/>
    </ItemGroup>

</Project>
