apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: domain-events-subscription
spec:
  topic: sekiban-events
  routes:
    default: /events
  pubsubname: pubsub
scopes:
- dapr-sample-event-relay