//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sekiban.Addon.Tenant.Properties {

    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValueObjectAttributes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValueObjectAttributes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Somu.Library.Properties.ValueObjectAttributes", typeof(ValueObjectAttributes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   半角英数字・記号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AsciiStringAcceptableCharacterTypes {
            get {
                return ResourceManager.GetString("AsciiStringAcceptableCharacterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角文字列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AsciiStringDisplayName {
            get {
                return ResourceManager.GetString("AsciiStringDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmailStringDisplayName {
            get {
                return ResourceManager.GetString("EmailStringDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringValueBaseDisplayName {
            get {
                return ResourceManager.GetString("StringValueBaseDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TelDisplayName {
            get {
                return ResourceManager.GetString("TelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角数字と半角ハイフンおよび半角プラス記号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TelStringAcceptableCharacterTypes {
            get {
                return ResourceManager.GetString("TelStringAcceptableCharacterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZipCodeDisplayName {
            get {
                return ResourceManager.GetString("ZipCodeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角英数字と半角ハイフン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZipCodeStringAcceptableCharacterTypes {
            get {
                return ResourceManager.GetString("ZipCodeStringAcceptableCharacterTypes", resourceCulture);
            }
        }
    }
}
