apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=localhost user=postgres password=postgres dbname=sekiban port=5432 sslmode=disable"
  - name: actorStateStore
    value: "true"
  - name: tableName
    value: "state"