apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
  metric:
    enabled: true
  api:
    allowed:
      - name: state
        version: v1
        protocol: http
      - name: pubsub
        version: v1  
        protocol: http