apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "localhost:4318"
      isSecure: false
      protocol: http
  metric:
    enabled: true
  features:
    - name: proxy.grpc
      enabled: true