// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sekiban.Dcb.Postgres;

#nullable disable

namespace Sekiban.Dcb.Postgres.Migrations
{
    [DbContext(typeof(SekibanDcbDbContext))]
    [Migration("20260822163309_AddPostgresTagHeadExpectedPositionCas")]
    partial class AddPostgresTagHeadExpectedPositionCas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sekiban.Dcb.Postgres.DbModels.DbEvent", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CausationId")
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutedUser")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("SortableUniqueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServiceId", "Id");

                    b.HasIndex("EventType");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_Events_ServiceId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ServiceId", "SortableUniqueId")
                        .HasDatabaseName("IX_Events_Service_SortableUniqueId");

                    b.ToTable("dcb_events", (string)null);
                });

            modelBuilder.Entity("Sekiban.Dcb.Postgres.DbModels.DbMultiProjectionState", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProjectorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProjectorVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BuildHost")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BuildSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("CompressedSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventsProcessed")
                        .HasColumnType("bigint");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOffloaded")
                        .HasColumnType("boolean");

                    b.Property<string>("LastSortableUniqueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer");

                    b.Property<string>("OffloadKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OffloadProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("OriginalSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("SafeWindowThreshold")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("StateData")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServiceId", "ProjectorName", "ProjectorVersion");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_MultiProjectionStates_UpdatedAt");

                    b.HasIndex("ServiceId", "ProjectorName")
                        .HasDatabaseName("IX_MultiProjectionStates_Service_ProjectorName");

                    b.ToTable("dcb_multi_projection_states", null, t =>
                        {
                            t.HasCheckConstraint("CK_MultiProjectionStates_OffloadConsistency", "(\"IsOffloaded\" = false AND \"StateData\" IS NOT NULL) OR (\"IsOffloaded\" = true AND \"OffloadKey\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Sekiban.Dcb.Postgres.DbModels.DbTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SortableUniqueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_Tags_EventId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_Tags_ServiceId");

                    b.HasIndex("SortableUniqueId")
                        .HasDatabaseName("IX_Tags_SortableUniqueId");

                    b.HasIndex("ServiceId", "Tag")
                        .HasDatabaseName("IX_Tags_Service_Tag");

                    b.HasIndex("ServiceId", "Tag", "SortableUniqueId")
                        .HasDatabaseName("IX_Tags_Service_Tag_SortableUniqueId");

                    b.ToTable("dcb_tags", (string)null);
                });

            modelBuilder.Entity("Sekiban.Dcb.Postgres.DbModels.DbTagHead", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<string>("HeadPosition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ServiceId", "Tag");

                    b.ToTable("dcb_tag_heads", null, t =>
                        {
                            t.HasCheckConstraint("CK_TagHeads_Position_NotEmpty", "\"HeadPosition\" IS NULL OR length(\"HeadPosition\") > 0");
                        });
                });

            modelBuilder.Entity("Sekiban.Dcb.Postgres.DbModels.DbTagHeadEnablementEpoch", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("EnabledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServiceId");

                    b.ToTable("dcb_tag_head_enablement_epochs", (string)null);
                });

            modelBuilder.Entity("Sekiban.Dcb.Postgres.DbModels.DbTagHeadViolation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectingWriter")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ObservedPosition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreviousHeadPosition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PreviousHeadWasEmpty")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "Tag", "DetectedAtUtc")
                        .HasDatabaseName("IX_TagHeadViolations_Service_Tag_Detected");

                    b.HasIndex("ServiceId", "Tag", "PreviousHeadWasEmpty", "PreviousHeadPosition", "ObservedPosition")
                        .IsUnique()
                        .HasDatabaseName("UX_TagHeadViolations_IdempotentRepair");

                    b.ToTable("dcb_tag_head_violations", null, t =>
                        {
                            t.HasCheckConstraint("CK_TagHeadViolations_Observed_NotEmpty", "length(\"ObservedPosition\") > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
