// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sekiban.Dcb.Postgres;

#nullable disable

namespace Sekiban.Dcb.Postgres.Migrations
{
    [DbContext(typeof(SekibanDcbDbContext))]
    partial class SekibanDcbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sekiban.Dcb.Postgres.DbModels.DbEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CausationId")
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutedUser")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("SortableUniqueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("SortableUniqueId")
                        .IsUnique()
                        .HasDatabaseName("IX_Events_SortableUniqueId");

                    b.HasIndex("Timestamp");

                    b.ToTable("dcb_events", (string)null);
                });

            modelBuilder.Entity("Sekiban.Dcb.Postgres.DbModels.DbMultiProjectionState", b =>
                {
                    b.Property<string>("ProjectorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProjectorVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BuildHost")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BuildSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("CompressedSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventsProcessed")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOffloaded")
                        .HasColumnType("boolean");

                    b.Property<string>("LastSortableUniqueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OffloadKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OffloadProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("OriginalSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SafeWindowThreshold")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("StateData")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProjectorName", "ProjectorVersion");

                    b.HasIndex("ProjectorName")
                        .HasDatabaseName("IX_MultiProjectionStates_ProjectorName");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_MultiProjectionStates_UpdatedAt");

                    b.ToTable("dcb_multi_projection_states", null, t =>
                        {
                            t.HasCheckConstraint("CK_MultiProjectionStates_OffloadConsistency", "(\"IsOffloaded\" = false AND \"StateData\" IS NOT NULL) OR (\"IsOffloaded\" = true AND \"OffloadKey\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Sekiban.Dcb.Postgres.DbModels.DbTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SortableUniqueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_Tags_EventId");

                    b.HasIndex("SortableUniqueId")
                        .HasDatabaseName("IX_Tags_SortableUniqueId");

                    b.HasIndex("Tag")
                        .HasDatabaseName("IX_Tags_Tag");

                    b.HasIndex("Tag", "SortableUniqueId")
                        .HasDatabaseName("IX_Tags_Tag_SortableUniqueId");

                    b.ToTable("dcb_tags", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
