using System.Text.Json.Serialization;

namespace Sekiban.Pure.Dapr.Actors;

/// <summary>
/// Response from command execution
/// </summary>
public record CommandResponse
{
    /// <summary>
    /// Whether the command execution was successful
    /// </summary>
    [JsonPropertyName("isSuccess")]
    public bool IsSuccess { get; init; }

    /// <summary>
    /// List of events generated by the command (Protobuf-serialized)
    /// </summary>
    [JsonPropertyName("eventPayloads")]
    public List<byte[]> EventPayloads { get; init; } = new();

    /// <summary>
    /// Event types corresponding to EventPayloads
    /// </summary>
    [JsonPropertyName("eventTypes")]
    public List<string> EventTypes { get; init; } = new();

    /// <summary>
    /// Error details if command failed (JSON-serialized)
    /// </summary>
    [JsonPropertyName("errorJson")]
    public string? ErrorJson { get; init; }

    /// <summary>
    /// The new version of the aggregate after command execution
    /// </summary>
    [JsonPropertyName("aggregateVersion")]
    public int AggregateVersion { get; init; }

    /// <summary>
    /// The aggregate state after command execution (optional, Protobuf-serialized)
    /// </summary>
    [JsonPropertyName("aggregateStatePayload")]
    public byte[]? AggregateStatePayload { get; init; }

    /// <summary>
    /// The aggregate state type
    /// </summary>
    [JsonPropertyName("aggregateStateType")]
    public string? AggregateStateType { get; init; }

    /// <summary>
    /// Response metadata
    /// </summary>
    [JsonPropertyName("metadata")]
    public Dictionary<string, string> Metadata { get; init; } = new();

    /// <summary>
    /// Creates a new CommandResponse
    /// </summary>
    public CommandResponse() { }

    /// <summary>
    /// Creates a successful CommandResponse
    /// </summary>
    public static CommandResponse Success(
        List<byte[]> eventPayloads,
        List<string> eventTypes,
        int aggregateVersion,
        byte[]? aggregateStatePayload = null,
        string? aggregateStateType = null,
        Dictionary<string, string>? metadata = null)
    {
        return new CommandResponse
        {
            IsSuccess = true,
            EventPayloads = eventPayloads,
            EventTypes = eventTypes,
            AggregateVersion = aggregateVersion,
            AggregateStatePayload = aggregateStatePayload,
            AggregateStateType = aggregateStateType,
            Metadata = metadata ?? new Dictionary<string, string>()
        };
    }

    /// <summary>
    /// Creates a failed CommandResponse
    /// </summary>
    public static CommandResponse Failure(
        string errorJson,
        Dictionary<string, string>? metadata = null)
    {
        return new CommandResponse
        {
            IsSuccess = false,
            ErrorJson = errorJson,
            Metadata = metadata ?? new Dictionary<string, string>()
        };
    }
}