name: Deploy Sekiban Document MCP to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'tools/SekibanDocumentMcpSse/**'
      - '.github/workflows/deploy_mcp_to_azure.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'sekibanmcp'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Create environment-specific local.json from secrets
        run: |
          cd tools/SekibanDocumentMcpSse/infrastructure/azure_appservice_minimal
          cat > $ENVIRONMENT.local.json << EOF
          {
            "resourceGroupName": "${{ secrets.AZURE_RESOURCE_GROUP_NAME }}",
            "location": "${{ secrets.AZURE_LOCATION }}",
            "mcpRelativePath": "../../"
          }
          EOF
          echo "Created $ENVIRONMENT.local.json with resource group: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}"

      - name: Deploy MCP App
        run: |
          cd tools/SekibanDocumentMcpSse/infrastructure/azure_appservice_minimal
          chmod +x code_deploy_mcp.sh
          ./code_deploy_mcp.sh $ENVIRONMENT
