name: nuget package release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-rc.1.22431.12
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Package settings
      run: |
        dotnet nuget add source --username USERNAME --password ${{secrets.TOMOHISA_PAT}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/J-Tech-Japan/index.json"
    - name: Restore dependencies
      run: |
        pushd ./src
        dotnet restore Sekiban.Lib.sln
    - name: Build with dotnet
      run: |
        pushd ./src
        dotnet build Sekiban.Lib.sln
    - name: Pack Core
      run: |
        pushd ./src/Sekiban.Core
        dotnet pack --configuration Release
        dotnet nuget push "bin/Release/JJ_Sekiban.Core.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.TOMOHISA_PAT}} --source "github"
    - name: Pack Testing
      run: |
        pushd ./src/Sekiban.Testing
        dotnet pack --configuration Release
        dotnet nuget push "bin/Release/JJ_Sekiban.Testing.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.TOMOHISA_PAT}} --source "github"
    - name: Pack Cosmos
      run: |
        pushd ./src/Sekiban.Infrastructure.Cosmos
        dotnet pack --configuration Release
        dotnet nuget push "bin/Release/JJ_Sekiban.Infrastructure.Cosmos.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.TOMOHISA_PAT}} --source "github"
    - name: Pack WebHelper
      run: |
        pushd ./src/Sekiban.Addon.Web
        dotnet pack --configuration Release
        dotnet nuget push "bin/Release/JJ_Sekiban.Addon.Web.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.TOMOHISA_PAT}} --source "github"
    - name: Pack TenantAddon
      run: |
        pushd ./src/Sekiban.Addon.Tenant
        dotnet pack --configuration Release
        dotnet nuget push "bin/Release/JJ_Sekiban.Addon.Tenant.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.TOMOHISA_PAT}} --source "github"
