name: nuget package release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        pushd ./
        dotnet nuget add source -n benchmarknightly https://www.myget.org/F/benchmarkdotnet/api/v3/index.json
        dotnet restore Sekiban.sln
    - name: Build with dotnet
      run: |
        pushd ./
        dotnet build Sekiban.sln -c Release
    - name: Pack Core DotNet
      run: |
        dotnet nuget push "src/Sekiban.Core/bin/Release/Sekiban.Core.DotNet.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json  
    - name: Pack Core
      run: |
        dotnet nuget push "src/Sekiban.Core/bin/Release/Sekiban.Core.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
    - name: Pack Blob
      run: |
        dotnet nuget push "src/Sekiban.Infrastructure.Azure.Storage.Blobs/bin/Release/Sekiban.Infrastructure.Azure.Storage.Blobs.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
    - name: Pack Cosmos
      run: |
        dotnet nuget push "src/Sekiban.Infrastructure.Cosmos/bin/Release/Sekiban.Infrastructure.Cosmos.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
    - name: Pack S3
      run: |
        dotnet nuget push "src/Sekiban.Infrastructure.Aws.S3/bin/Release/Sekiban.Infrastructure.Aws.S3.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
    - name: Pack Dynamo
      run: |
        dotnet nuget push "src/Sekiban.Infrastructure.Dynamo/bin/Release/Sekiban.Infrastructure.Dynamo.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
    - name: Pack Testing
      run: |
        dotnet nuget push "src/Sekiban.Testing/bin/Release/Sekiban.Testing.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
    - name: Pack IndexedDb
      run: |
        dotnet nuget push "src/Sekiban.Infrastructure.IndexedDb/bin/Release/Sekiban.Infrastructure.IndexedDb.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
    - name: Pack Web
      run: |
        dotnet nuget push "src/Sekiban.Web/bin/Release/Sekiban.Web.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
    - name: Pack Cosmos Aspire
      run: |
        dotnet nuget push "src/Sekiban.Aspire.Infrastructure.Cosmos/bin/Release/Sekiban.Aspire.Infrastructure.Cosmos.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
    - name: Pack Cosmos Postgres
      run: |
        dotnet nuget push "src/Sekiban.Infrastructure.Postgres/bin/Release/Sekiban.Infrastructure.Postgres.${{ github.event.release.tag_name }}.nupkg" --api-key ${{secrets.NUGET_APIKEY}}  --source https://api.nuget.org/v3/index.json
        