name: Run Backend Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**"
      - "samples/**"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**"
      - "samples/**"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-rc.1.22431.12
    - name: Package settings
      run: |
        dotnet nuget add source --username USERNAME --password ${{secrets.TOMOHISA_PAT}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/J-Tech-Japan/index.json"
    - name: Restore dependencies
      run: |
        dotnet restore Sekiban.sln
    - name: Build with dotnet
      run: |
        dotnet build Sekiban.sln
    - name: Test dotnet
      run: |
        dotnet test Sekiban.sln
