name: Run Backend Performance Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**"
      - "samples/**"
concurrency: 
  group: CosmosDbConnect
  cancel-in-progress: false
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Package settings
      run: |
        dotnet nuget add source --username USERNAME --password ${{secrets.TOMOHISA_PAT}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/J-Tech-Japan/index.json"
    - name: Secret Settings
      run: |
        pushd ./test/Sekiban.Consistency.Test.CosmosDb
        dotnet user-secrets set "Sekiban:Default:CosmosDbEndPointUrl" ${{secrets.TEST_COSMOS_ENDPOINT}}
        dotnet user-secrets set "Sekiban:Default:CosmosDbAuthorizationKey" ${{secrets.TEST_COSMOS_SECRET}}
        dotnet user-secrets set "Sekiban:Secondary:CosmosDbEndPointUrl" ${{secrets.TEST_COSMOS_ENDPOINT}}
        dotnet user-secrets set "Sekiban:Secondary:CosmosDbAuthorizationKey" ${{secrets.TEST_COSMOS_SECRET}}
        dotnet user-secrets set "Sekiban:Default:CosmosDbDatabase" "GithubActions"
        dotnet user-secrets set "Sekiban:Secondary:CosmosDbDatabase" "GithubActions"
    - name: Restore dependencies
      run: |
        dotnet restore Sekiban.sln
    - name: Build with dotnet
      run: |
        dotnet build Sekiban.sln
    - name: Test dotnet
      run: |
        dotnet test Sekiban.sln  --filter "Category=Performance"
