name: Run Backend Regular Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**"
      - "samples/**"
concurrency:
  group: CosmosDbConnect
  cancel-in-progress: false
jobs:
  regularAggregateTest:
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        ports:
          - 8081:8081
        env:
          PROTOCOL: https
      max-parallel: 4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Secret Settings
      run: |
        pushd ./tests/Sekiban.Test.Abstructs
        dotnet user-secrets set "ConnectionStrings:SekibanCosmos" "AccountEndpoint=https://cosmosdb:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRW1F2=="
        dotnet user-secrets set "ConnectionStrings:SekibanPostgresDefault" "Host=postgres;Port=5432;Database=mydb;Username=myuser;Password=mypassword;"
    - name: Restore dependencies
      run: |
        dotnet nuget add source -n benchmarknightly https://www.myget.org/F/benchmarkdotnet/api/v3/index.json
        dotnet restore Sekiban.sln
    - name: Test Build
      run: |
        dotnet build Sekiban.sln -c Release
    - name: Test dotnet FeatureCheck .NET9
      run: |
        dotnet test tests/FeatureCheck.Test/FeatureCheck.Test.csproj  --filter "Category!=Flaky&Category!=Performance" -v m -c Release -m:1 -f net9.0
